usuarios/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


app_name = 'usuarios'

urlpatterns = [
    path('nuevo/', views.NuevoUsuario.as_view(), name='nuevo'),
    path('municipios/', views.obtiene_municipios, name='municipios'),
    path('lista/', views.UsuariosList.as_view(), name='lista'),
    path('eliminar/<int:pk>', views.UsuariosEliminar.as_view(), name='eliminar'),
    path('editar/', views.UsuariosActualizar.as_view(), name='editar'),
    path('ver/<int:pk>', views.UsuariosDetalle.as_view(), name='ver'),
    path('login/', views.LoginUsuario.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.NuevoUsuario.as_view(), name='signup'),
    path('activar/<slug:uid64>/<slug:token>', views.ActivarCuenta.as_view(), name='activar'),
    path('cambia-grupo/<int:id_gpo>/<int:id_usuario>', views.cambia_grupo, name='cambia-grupo'),
    path('modificar-grupos/<int:id>', views.modificar_usuario_grupo, name='modificar_usuario_grupo'),


]

videojuegos/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categorias/', include('videojuego.urls_categoria')),
    path('videojuegos/', include('videojuego.urls_videojuego')),
    path('usuarios/', include('usuarios.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


class Usuario(User):
    estado = models.ForeignKey("usuarios.Estado", verbose_name="Estado",  on_delete=models.CASCADE)
    municipio = models.ForeignKey("usuarios.Municipio", verbose_name="Municipio",  on_delete=models.CASCADE)
    foto = models.ImageField("Foto de perfil", upload_to='perfiles', blank=True, null=True)

class Estado(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

    
class Municipio(models.Model):
    nombre = models.CharField(max_length=50)
    estado = models.ForeignKey("usuarios.Estado", verbose_name="Estado",on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre
      

usuarios/forms.py
from django import forms
from .models import Usuario


class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario

        fields = ('first_name','username','password','email','estado','municipio','foto')

        widgets = {
            'password': forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Contraseña'}),
            'estado': forms.Select(attrs={'class':'form-control'})
        }

    def save(self, commit=True):
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

usuarios/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin
from django.contrib.messages.views import SuccessMessageMixin
from .token import token_activacion
from .models import Usuario, Municipio, Estado
from .forms import UsuarioForm
from django.contrib.auth.models import Group

class NuevoUsuario(CreateView):
    model = Usuario
    form_class = UsuarioForm
    # permission_required = 'usuarios.add_usuario'
    extra_context = {'etiqueta': ('Nuevo'), 
    'boton': ('Agregar'),
    'us_nuevo': True}
    success_url = reverse_lazy('usuarios:login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        dominio = get_current_site(self.request) #toma el dominio actual
        uid = urlsafe_base64_encode(force_bytes(user.id))
        token = token_activacion.make_token(user)
        mensaje = render_to_string('confirmar_cuenta.html',
            {
                'usuario': user,
                'dominio': dominio,
                'uid': uid,
                'token': token
            }
        )
        asunto = 'Activa cuenta videojuegos'
        to = user.email
        email = EmailMessage(
            asunto,
            mensaje,
            to=[to]
        )
        email.content_subtype = 'html'
        email.send()

        return super().form_valid(form)


def obtiene_municipios(PermissionRequiredMixin,request):
    # estado = get_object_or_404(Estado, id=id_estado)
    if request.method == 'GET':
        return JsonResponse({'error':'Petición incorrecta'}, safe=False,  status=403)
    id_estado = request.POST.get('id')
    municipios = Municipio.objects.filter(estado_id = id_estado)
    json = []
    if not municipios:
        json.append({'error':'No se encontrar municipios para ese estado'})
        
    for municipio in municipios:
        json.append({'id':municipio.id, 'nombre':municipio.nombre})
    return JsonResponse(json, safe=False)

class UsuariosList(PermissionRequiredMixin,ListView):
    paginate_by = 5
    permission_required = 'usuarios.view_usuario'
    model = Usuario
    lista_grupos = Group.objects.all()

    extra_context = {'us_lista' : True,
                    'lista_grupos': lista_grupos}
    template_name = 'usuarios:lista'

class UsuariosEliminar(PermissionRequiredMixin,DeleteView):
    model = Usuario
    success_url = reverse_lazy('usuarios:lista')


class UsuariosActualizar(PermissionRequiredMixin, SuccessMessageMixin,UpdateView):
    # template_name = 'usuario_detail.html'
    model = Usuario
    permission_required = 'usuarios.edit_usuario'
    form_class = UsuarioForm
    extra_context = {'etiqueta': 'Actualizar', 'boton': 'Guardar'}
    success_url = reverse_lazy('usuarios:editar')
    success_message = "El usuario %(first_name)s se actualizo con exito"

    def get_object(self, queryset=None):
        pk = self.request.user.pk
        obj = Usuario.objects.get(pk=pk)
        return obj

    # def get_success_url(self):
    #     pk = self.kwargs.get(self.pk_url_kwarg)
    #     url = reverse_lazy('usuarios:ver', kwargs={'pk':pk})
    #     return url

class UsuariosDetalle(PermissionRequiredMixin,DetailView):
    model = Usuario
    permission_required = 'usuarios.view_usuario'

class LoginUsuario(LoginView):
    template_name = 'login.html'
    #form_class = AuthenticationForm

    def get_success_url(self):
        self.request.session['cuantos'] = 0
        self.request.session['total'] = 0.0
        self.request.session['juegos'] = {}

        return super().get_success_url()

class ActivarCuenta(TemplateView):
    def get(self, request, *args, **kwargs):
        try:
            uid = urlsafe_base64_decode(kwargs['uid64'])
            token = kwargs['token']
            user = Usuario.objects.get(id=uid)
        except:
            user = None

        if user and token_activacion.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(self.request, 'Cuenta activada con éxito')
        else:
            messages.error(self.request, 'Token inválido, contacta al administrador')

        return redirect('usuarios:login')

def cambia_grupo(request,id_gpo, id_usuario):
    grupo = Group.objects.get(id= id_gpo)
    usuario = Usuario.objects.get(id= id_usuario)
    permission_required = 'usuarios.edit_usuario'
    if grupo in usuario.groups.all():
        if usuario.groups.count() <= 1: #
            messages.error(request, 'El usuario debe pertenecer a un grupo como minimo')
        else:
            usuario.groups.remove(grupo)
            messages.success(request, f'El usuario {usuario} ya no  pertenece al grupo {grupo}')

    else:
        usuario.groups.add(grupo)
        messages.success(request, f'El usuario {usuario} se agrego al grupo {grupo}')
    return redirect('usuarios:lista')


def modificar_usuario_grupo(request, id):
    
    grupos = [grupo.id for grupo in Group.objects.all()]
    usuario = Usuario.objects.get(id=id)
    usuario.groups.clear()
    permission_required = 'usuarios.edit_usuario'

    for item in request.POST:
        if request.POST[item] == 'on':
            usuario.groups.add(Group.objects.get(id=int(item)))

        messages.success(request, f'El usuario {usuario} pertenece al grupo')

    return redirect('usuarios:lista')

usuarios/templates/confirmar_cuenta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar cuenta</title>
</head>
<body>
    <div>
        <h3>Validar cuenta</h3>
        <p>Hola {{usuario.username}}</p>
        <p>Para completar tu registro en el sistema de <b>Videojuegos</b>
           debes dar click en el siguiente enlace
        </p>
        <br>
        <hr>
        <p>
            <a href="http://{{dominio}}{% url 'usuarios:activar' uid64=uid token=token %}">
                Activar cuenta
            </a>
        </p>
        <br>
        <p>Saludos!!!!</p>
    </div>
</body>
</html>

usuarios/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>Login de los Videojuegos</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'favicon.png' %}"> 
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'css/portal.css' %}">

</head> 

<body class="app app-login p-0">    
	
	{% if form.errors %}
		<div class="alert alert-warning">
			<p>Usuario no encontrado</p>
		</div>
	{% endif %}
		
	{% if messages %}
		{% for message in messages  %}
			<div class="alert alert--{% if message.tags == 'error' %}danger{%else%}success{%endif%}">
				{{message}}
			</div>
		{% endfor %}
	{% endif %}
		
	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="index.html"><img class="logo-icon mr-2" src="{% static 'images/app-logo.svg' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-5">Log in to Videojuegos</h2>
			        <div class="auth-form-container text-left">
						<form class="auth-form login-form" method="POST">
							{% csrf_token %}       
							<div class="email mb-3">
								<label class="sr-only" for="signin-email">Usuario</label>
								<input id="id_username" name="username" type="text" class="form-control signin-email" placeholder="Nombre de usuario" required="required">
							</div><!--//form-group-->
							<div class="password mb-3">
								<label class="sr-only" for="signin-password">Contraseña</label>
								<input id="id_password" name="password" type="password" class="form-control signin-password" placeholder="Contraseña" required="required">
								<div class="extra mt-3 row justify-content-between">
									<div class="col-6">
										<div class="form-check">
											<input class="form-check-input" type="checkbox" value="" id="RememberPassword">
											<label class="form-check-label" for="RememberPassword">
											Recordar
											</label>
										</div>
									</div><!--//col-6-->
									<div class="col-6">
										<div class="forgot-password text-right">
											<a href="reset-password.html">Olvide la contraseña</a>
										</div>
									</div><!--//col-6-->
								</div><!--//extra-->
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" class="btn app-btn-primary btn-block theme-btn mx-auto">Ingresar</button>
							</div>
							<input type="hidden" name="next" value={{next}}>
						</form>
						
						<div class="auth-option text-center pt-5">No tengo cuenta<a class="text-link" href="{% url 'usuarios:nuevo' %}" >Crear</a>.</div>
					</div><!--//auth-form-container-->	

			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
			        <small class="copyright">Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">
			    <div class="d-flex flex-column align-content-end h-100">
				    <div class="h-100"></div>
				    <div class="overlay-content p-3 p-lg-4 rounded">
					    <h5 class="mb-3 overlay-title">Explore Portal Admin Template</h5>
					    <div>Portal is a free Bootstrap 5 admin dashboard template. You can download and view the template license <a href="https://themes.3rdwavemedia.com/bootstrap-templates/admin-dashboard/portal-free-bootstrap-admin-dashboard-template-for-developers/">here</a>.</div>
				    </div>
				</div>
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    
    </div><!--//row-->


</body>
</html> 


usuarios/templates/signup.html

{% load static %}
<!DOCTYPE html>
<html lang="en"> 
	
<head>
    <title>Registro nuevo usuario</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">   
    <link rel="shortcut icon" href="{% static 'favicon.png' %}"> 
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'js/all.min.js' %}"></script>


    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'css/portal.css' %}">

</head> 

<body class="app app-signup p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="index.html"><img class="logo-icon mr-2" src="{% static 'images/app-logo.svg' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-4">Registro nuevo usuario</h2>					
	
					<div class="auth-form-container text-left mx-auto">
                        {% block css %}
                        {% endblock css %}
                            
                        {% block js %}
    						<script src="{% static 'js/funciones.js' %}"></script>    

                        {% block contenido %}
                            <h1>{{etiqueta}} usuarios</h1>
                            <form method="post" enctype="multipart/form-data" >
                                {% csrf_token %}
                                {{form.as_p}}
                                <button type="submit" class="btn btn-success">{{boton}}</button>
                            </form>
                        {% endblock contenido %}
                        
						<div class="auth-option text-center pt-5">Already have an account? <a class="text-link" href="login.html" >Log in</a></div>
					</div><!--//auth-form-container-->	
					
				    
			    </div><!--//auth-body-->
		    
			
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    
    
    </div><!--//row-->
    

</body>
{% endblock js %}
</html>

    
